### ISSUE TITLE
Error when installing more than one choco font package

### ISSUE THREAD

**Issue by KZeronimo** [chocolatey/boxstarter#455]
### What You Are Seeing?

Strange error when installing font choco packages via Boxtarter

### What Is Expected?

Both choco packages install successfully which is what happens when executing outside of Boxstarter

### How Did You Get This To Happen? (Steps to Reproduce)

Create a Boxstarter package with the following

> cinst cascadia-code-nerd-font
cinst sourcecodepro

### Output Log

edit: removed public gist of logs - key log output

> ERROR: Cannot add type. The type name 'FontResource.AddRemoveFonts' already exists.
The install of cascadia-code-nerd-font was NOT successful.

**Comment by flcdrg** [comment]
The install apperas to be failing because it is trying to run extensions\New-FontResourceType.ps1 more than once (which has the call to `Add-Type`)

https://chocolatey.org/packages/chocolatey-font-helpers.extension mentions that there is a multiple font option, which https://chocolatey.org/packages/cascadia-code-nerd-font is not using.

However I just tested installing cascadia-code-nerd-font myself and can confirm it installs without error.

This is strange!

**Comment by pauby** [comment]
At a guess I'd say this is happening as Boxstarter runs that script in the same context. Boxstarter doesn't directly call choco so I'm assuming sheave use it's PowerShell host that would isolated package installation. So when you're running the second `cinst` that resource is already there.

That's a guess. I'm not in a position to check just now.

A workaround would be to put a reboot between them?

@mwallner thoughts?

**Comment by mwallner** [comment]
@flcdrg and @pauby both already got to the correct conclusion: 

Since Boxstarter doesn't spawn a separate PowerShell host for each `cinst` the session scope is being shared, meaning all `Add-Type` calls may influence consecutive installations. 
https://chocolatey.org/packages/chocolatey-font-helpers.extension always runs `Add-Type $fontCSharpCode` in `New-FontResourceType`, - no matter if it's already present or not. (which is totally fine for a 'normal Chocolatey use case')

tbh, despite heavy Boxstarter usage this behavior never occurred in my environments, yet it's definitely something we haven't thought of.

as @pauby suggested, a forced reboot between the package installations may be used to bypass the error. (imo it's more a dirty hack than a workaround 😄)

could by 'fixed' by something like this:
```
cinst sourcecodepro

if (-Not (Test-Path "C:\rebootmarker")) {
  Get-Date | Out-File "C:\rebootmarker"
  Invoke-Reboot
}

cinst cascadia-code-nerd-font
```

I think the "installation scope separation" is something we should put on our agenda for the next Boxstarter release.

**Comment by flcdrg** [comment]
A side comment to this: I happened to notice that the source code for the font extension package doesn't actually match what's in the latest version of the package. Might add a comment on the package for the maintainers

**Comment by KZeronimo** [comment]
Hi @mwallner et al - thanks for looking into this - besides the mentioned "installation scope separation" topic for Boxstarter is there a recommendation for choco package authors/maintainers to be more defensive with Add-Type

I understand it's fine when running outside of Boxstarter but I think a lot of the choco usage is in the context of Boxstarter (at least for us)

FWIW automated font installation on Windows is harder than it should be - we have a pretty rich Boxstarter script to initialize our dev machines and the pain point is installing fonts?!?

Feel free to disposition this issue as you see fit

**Comment by pauby** [comment]
I really don't see a way around this at the moment. Looking at the help for Add-Type, under `Notes` it says:

```
Type names and namespaces must be unique within a session. You can't unload a type or change it. If you need
        to change the code for a type, you must change the name or start a new PowerShell session. Otherwise, the
        command fails.
```
So in the context of Boxstarter I'm not sure what we can do given the current design. We need to start a new session and the only way that can be done is via a reboot. Anything else would likely require major re-engineering of Boxstarter. If anybody disagrees please feel free to add here.

Long term this may be resolved by #394, if that goes ahead.

**Comment by flcdrg** [comment]
A possible mitigation might be to submit a patch to https://chocolatey.org/packages/chocolatey-font-helpers.extension so that the `Add-Type` logic can be run multiple times without error.

A followup to my comment on that package notes that @teknowledgist is now maintaining the source under https://github.com/teknowledgist/Chocolatey-packages/tree/master/extensions/chocolatey-font-helpers.extension

**Comment by KZeronimo** [comment]
@flcdrg - I forked the chocolatey-font-helpers.extension from @bcurran3  (it was unclear exactly who was maintaining) and submitted a PR wrapping Add-Type with an existence check.  I *think* that should fix the issue.

I suppose I can do the same for @teknowledgist implementation

BTW - when there are multiple maintainers of a choco package how do you tell which one is "shipping"

**Comment by mwallner** [comment]
ok ok ok ... I've cracked my head against this problem, and tbh, fixing the font packages is something we should do - but imo this is not a proper solution to the current problem @KZeronimo is facing.

I just came up with a crazy idea that might actually work and probably could be implemented in Boxstarter if we spend a little more thought on it! :smile:

@KZeronimo try the following:
at the beginning of your boxstarter script, manually add the type that's required in the font packages.
```
   $fontCSharpCode = @'
   using System;
   using System.Collections.Generic;
   using System.Text;
   using System.IO;
   using System.Runtime.InteropServices;

   namespace FontResource {
       public class AddRemoveFonts {
           private static IntPtr HWND_BROADCAST = new IntPtr(0xffff);

           [DllImport("gdi32.dll")]
           static extern int AddFontResource(string lpFilename);

           [DllImport("gdi32.dll")]
           static extern int RemoveFontResource(string lpFileName);

           [return: MarshalAs(UnmanagedType.Bool)]
           [DllImport("user32.dll", SetLastError = true)]
           private static extern bool PostMessage(IntPtr hWnd, WM Msg, IntPtr wParam, IntPtr lParam);

           public enum WM : uint {
               FONTCHANGE = 0x001D
           }

           public static int AddFont(string fontFilePath) {
               FileInfo fontFile = new FileInfo(fontFilePath);
               if (!fontFile.Exists) { return 0; }
               try {
                   int retVal = AddFontResource(fontFilePath);
                   bool posted = PostMessage(HWND_BROADCAST, WM.FONTCHANGE, IntPtr.Zero, IntPtr.Zero);
                   return retVal;
               }
               catch { return 0; }
           }

           public static int RemoveFont(string fontFileName) {
               try {
                   int retVal = RemoveFontResource(fontFileName);
                   bool posted = PostMessage(HWND_BROADCAST, WM.FONTCHANGE, IntPtr.Zero, IntPtr.Zero);
                   return retVal;
               }
               catch { return 0; }
           }
       }
   }
'@
   Add-Type $fontCSharpCode
```

right after that, add a custom `Add-Type` function like this:
```
function Add-Type { Write-Host "yolo!" }
```

after that, do your
```
cinst somefont
cinst some_other_font
cinst whatever
```

at the very end of your boxstarter package, remove the custom added `Add-Type` function again:
```
Remove-Item function:Add-Type
```

ta-da :smile:

**Comment by mwallner** [comment]
@pauby @flcdrg see comment above, I think I might be onto something.
If we could _rename_ the `Add-Type` function during boxstarter is active and wrap it in a "fault tolerant" equivalent which internally calls the `Add-Type` of module `Microsoft.PowerShell.Utility` we could fix this in a semi-clean manner which woulnd't requrie package maintainers to make any change.

**Comment by teknowledgist** [comment]
I just pushed v0.3 of the Chocolatey Font Helpers extension that should resolve the issue of trying to re-add the type and (hopefully) give better error messaging for an unusual font add/remove failure.

Let me know if it works (or not) for you.

**Comment by KZeronimo** [comment]
@mwallner - take a look [here](https://gist.github.com/KZeronimo/f9cd01a305b031f9dae86f818f88e7b2)

Still getting `ERROR: Cannot add type. The type name 'FontResource.AddRemoveFonts' already exists.`

@teknowledgist  will try the updated extension when it is approved (not sure how to test before that)

**Comment by mwallner** [comment]
thanks for the feedback @KZeronimo! I'm not entirely sure why this doesn't work in Boxstarter context, yet seems to work just fine in a plain poweshell prompt. :confused:
```
$fontCSharpCode = .. you know what ..

Add-Type $fontCSharpCode # actually adds the type

function Add-Type { Write-Host "yolo!" }
# cinst sourcecodepro
Add-Type $fontCSharpCode # prints yolo
# cinst cascadia-code-nerd-font
Add-Type $fontCSharpCode # prints yolo
# cinst notepadplusplus
Add-Type $fontCSharpCode # prints yolo

Remove-Item function:Add-Type
```

**Comment by flcdrg** [comment]
@KZeronimo the new 0.0.3 package is now approved, so give it a try.

I suspect installing the extension explicitly would also have worked. eg. add  `choco install chocolatey-font-helpers.extension --version=0.0.3` before your font packages.

**Comment by KZeronimo** [comment]
@flcdrg - yep was trying that - I looked in the font packages I'm trying in this example - **sourcecodepro** and **cascadia-code-nerd-font** both don't seem to use the font extensions - it looks like they just include the boilerplate `Add-Font` and `Remove-Font` provided by MSFT which won't have the type existence check of the updated extension by @teknowledgist 

The idea floated by @mwallner still might be useful for font packages not leveraging the choco font extension

See [my attempt](https://gist.github.com/KZeronimo/a5619bd6a06feedd6cb26ef17a673c74) - my thinking was that if I could install 2 fonts via `Install-ChocolateyFont` within the context of Boxstarter that would be a valid test

Unfortunately, I must be missing something in my understanding of how to properly use the choco font extension

What's a quick way to test the updated choco font extension?

**Comment by flcdrg** [comment]
@KZeronimo cascadia-code-nerd-font uses the extension, but yes unfortunately sourcecodepro doesn't - older font packages probably didn't know about it when they were created.

**Comment by KZeronimo** [comment]
@flcdrg - do you see anything wrong with the test I'm trying to do?

**Comment by teknowledgist** [comment]
Sorry!  🤦‍♂️  I think (hope!) it's fixed now with v0.0.3.1.  cascadia-code-nerd-font is installing now at least.

*(Anyone with C# error handling skills is welcome to contribute.  😄 )*

**Comment by KZeronimo** [comment]
@teknowledgist it looks like 0.0.3.1 is functioning as expected - I tested `Install-ChocolateyFont` and `Uninstall-ChocolateyFont` (single and multiple).  I can also confirm the type existence check fixes the error reported here

The issue of legacy font packages that don't use the extension is a maintenance item

@flcdrg @mwallner  - let me know if you want me to try anything else in the context of Boxstarter and the idea of the `Add-Type` intercept
